<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Official Response</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1f2933; font-size: 12px; line-height: 1.6; }
        .header { margin-bottom: 24px; }
        .header h1 { margin: 0 0 6px; font-size: 22px; }
        .meta { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .meta th, .meta td { border: 1px solid #d9e2ec; padding: 6px 8px; text-align: left; }
        .meta th { width: 180px; background: #f7fafc; }
        .body-copy { border: 1px solid #d9e2ec; padding: 16px; background: #fbfdff; }
        .footer { margin-top: 28px; color: #52606d; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Official Response</h1>
        <div>Issued by {{ $issuerLabel }}</div>
    </div>

    <table class="meta" cellspacing="0" cellpadding="0">
        <tbody>
            <tr><th>Tracking Code</th><td>{{ $serviceRequest->tracking_code }}</td></tr>
            <tr><th>Request ID</th><td>#{{ $serviceRequest->id }}</td></tr>
            <tr><th>Citizen</th><td>{{ $serviceRequest->user?->name ?? '-' }}</td></tr>
            <tr><th>Service</th><td>{{ $serviceRequest->service?->name ?? '-' }}</td></tr>
            <tr><th>Office</th><td>{{ $serviceRequest->service?->governmentOffice?->name ?? '-' }}</td></tr>
            <tr><th>Municipality</th><td>{{ $serviceRequest->service?->governmentOffice?->municipality?->name ?? '-' }}</td></tr>
            <tr><th>Current Status</th><td>{{ $serviceRequest->status }}</td></tr>
            <tr><th>Issued At</th><td>{{ now()->format('Y-m-d H:i') }}</td></tr>
        </tbody>
    </table>

    <div class="body-copy">
        {!! nl2br(e($summary)) !!}
    </div>

    <div class="footer">
        This PDF was generated by the E-Services platform for official request follow-up.
    </div>
</body>
</html>
